### PR TITLE
Fix Estimates of Remaining Ballots to Audit

### LINKED ISSUE #699: In Intermediate County Audit Report, one candidate with no votes is listed
See RLA Tool Feedback #2 (the 38-pager), item 34.

One candidate with no votes is listed, but other candidates with no votes are not listed.

### PR DESCRIPTION
**Pull request by dmzimmerman**
This fixes several issues (some of which don't have tickets but were reported in testing) related to computation of remaining ballots to audit, computation of discrepancies in certain cases, and report generation. Essentially:

- during tabulation, the `losers` set for each contest was incompletely initialized: it only included one choice with each vote total, so if multiple choices got 0 votes, only one was a `loser` and the others... disappeared. That made the discrepancy calculations unpredictable - even though the math behind them was correct, the data set they were working from was wrong. This is also why reports only included a single candidate that received 0 votes. This has been fixed.
- the inconsistency in the remaining number of ballots to audit arose from a calculation (referenced in #695) that we were doing to give an estimate of that remaining number based on discrepancy rates. It was using the percentage of audited ballots with discrepancies _at the time of recalculation_, but only recalculating when a discrepancy was reported. So, discrepancies that occurred earlier had a larger impact on the estimate than if they occurred later, because they represented a larger percentage of the audited ballots. The _optimistic_ estimate - the one from the RLA computation that uses the numbers of discrepancies detected but assumes no discrepancies going forward - was always correct, and the audit calculations as far as finishing the audit were always correct, but that was not what was being displayed. 

Closes #699

### CODE REVIEW

File: server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java [hunk 1]
```diff
@@ -542,7 +542,7 @@ public static boolean submitAuditCVR(final CountyDashboard the_cdb,
                        the_audit_cvr.id() + " for county " + the_cdb.id() + 
                        ", cvr " + the_cvr_under_audit.id());
     }
-
+    Persistence.flush();
```
Comment (kiniry) [inline server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java]: @dmz tells me that this `flush` is to ensure that a later `read` is guaranteed to see the earlier changes.

File: server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java [hunk 2]
```diff
@@ -648,8 +648,10 @@ public static boolean audited(final CountyDashboard the_cdb,
         for (int i = 0; i < the_count; i++) {
           ca.recordDiscrepancy(discrepancy.getAsInt());
         }
+        discrepancies.add(ca.auditReason());
       }
-      discrepancies.add(ca.auditReason());
+      ca.signalBallotAudited();
+      Persistence.saveOrUpdate(ca);
```
Comment (kiniry) [inline server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java]: These are not necessary, but not harmful.

File: server/eclipse-project/src/main/java/us/freeandfair/corla/model/CVRAuditInfo.java [hunk 3]
```diff
@@ -243,7 +243,7 @@ public void setDiscrepancy(final Set<AuditReason> the_reasons) {
    * as a disagreement in a contest audited for that reason.
    */
   public Set<AuditReason> disagreement() {
-    return Collections.unmodifiableSet(my_discrepancy);
+    return Collections.unmodifiableSet(my_disagreement);
```
Comment (kiniry) [inline server/eclipse-project/src/main/java/us/freeandfair/corla/model/CVRAuditInfo.java]: Whoops.  That's a cut-and-paste error originally.  We would not have noticed since we were focused on discrepancies.

File: server/eclipse-project/src/main/java/us/freeandfair/corla/model/CountyContestResult.java [hunk 4]
```diff
@@ -254,16 +254,22 @@ public Contest contest() {
...
     }
-    final Iterator<Entry<Integer, String>> iterator = 
+    
+    final Iterator<Entry<Integer, List<String>>> iterator = 
         sorted_totals.entrySet().iterator();
     while (iterator.hasNext()) {
-      final Entry<Integer, String> entry = iterator.next();
-      result.add(entry.getValue());
+      final Entry<Integer, List<String>> entry = iterator.next();
+      result.addAll(entry.getValue());
```
Comment (kiniry) [inline server/eclipse-project/src/main/java/us/freeandfair/corla/model/CountyContestResult.java]: That's the important bit.

File: server/eclipse-project/src/main/java/us/freeandfair/corla/model/CountyContestResult.java [hunk 5]
```diff
@@ -477,33 +483,37 @@ public void addCVR(final CastVoteRecord the_cvr) {
...
-    Entry<Integer, String> entry = null;
+    Entry<Integer, List<String>> entry = null;
     int votes = 0;
-    while (iterator.hasNext() && my_winners.size() < my_votes_allowed) {
-      entry = iterator.next();
+    while (vote_total_iterator.hasNext() && my_winners.size() < my_votes_allowed) {
+      entry = vote_total_iterator.next();
       votes = entry.getKey();
-      my_winners.add(entry.getValue());
+      my_winners.addAll(entry.getValue());
```
Comment (kiniry) [inline server/eclipse-project/src/main/java/us/freeandfair/corla/model/CountyContestResult.java]: And these, of course.
