### PR TITLE
CVR File Format Changes

### LINKED ISSUE #656: Revised CVR file format; new error messages needed for upload
To comply with Colorado law protecting voter anonymity, CDOS will ask Counties to remove the "counting group" column from the CVR file before hashing and uploading the file. 

To do:

1. alter server-side as necessary to process file without the column
2. if the column of the CVR file has not been deleted, refuse to import contents to db
3. if the column of the CVR file has not been deleted, give County user an error message:
"Import failed. Please remove Counting Group column, rehash and re-upload."

### PR DESCRIPTION
**Pull request by dmzimmerman**
Enables the prohibition of certain columns in the CVR file, and better error reporting, while also ensuring that the files contain the columns we need. 

Closes #656, including any future columns we decide to prohibit with a very, very minor change.

### CODE REVIEW

File: server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/CVRExportImport.java [hunk 1]
```diff
@@ -169,15 +171,18 @@ private void parseFile(final Response the_response, final UploadedFile the_file)
...
-                       ": " + e);
+      Main.LOGGER.info("could not parse malformed CVR export (file " + the_file.id() + 
+                       "): " + e);
       try {
         cleanup(the_file.countyID());
       } catch (final PersistenceException ex) {
         // if we couldn't clean up, there's not much we can do about it
       }
-      badDataContents(the_response, "malformed CVR export file " + the_file.id());
+      badDataContents(the_response, "malformed CVR export (file " + the_file.id() + ")");
```
Comment (ranweiler) [inline server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/CVRExportImport.java]: It would be helpful to also include the file name in this response.

Comment (ranweiler) [reply server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/CVRExportImport.java]: (and the above, whenever we are reporting an error about a file)

File: server/eclipse-project/src/main/java/us/freeandfair/corla/csv/DominionCVRExportParser.java [hunk 2]
```diff
@@ -358,6 +386,51 @@ private CastVoteRecord extractCVR(final CSVRecord the_line) {
...
+    
+    if (result) {
+      result &= my_columns.get(CVR_NUMBER_HEADER) != null;
+      result &= my_columns.get(TABULATOR_NUMBER_HEADER) != null;
+      result &= my_columns.get(BATCH_ID_HEADER) != null;
+      result &= my_columns.get(RECORD_ID_HEADER) != null;
+      result &= my_columns.get(IMPRINTED_ID_HEADER) != null;
+      result &= my_columns.get(BALLOT_TYPE_HEADER) != null;
+      if (!result) {
+        my_error_message = "missing required columns in import file";
```
Comment (ranweiler) [inline server/eclipse-project/src/main/java/us/freeandfair/corla/csv/DominionCVRExportParser.java]: Could we build up a list of the missing column names, and include them in the error message?

Comment (dmzimmerman) [reply server/eclipse-project/src/main/java/us/freeandfair/corla/csv/DominionCVRExportParser.java]: Yes. Yes we can.
