### PR TITLE
Fix risk limit step buttons

### LINKED ISSUE #611: Ensure risk limit form state change when up/down buttons used
Keyboard entry always changes both the apparent and internal form state. Currently, it looks like using those buttons does not change the internal form state, but only the external. Investigate, and ensure either entry method can be used.

### PR DESCRIPTION
**Pull request by ranweiler**
Closes #611.

### CODE REVIEW

File: client/src/component/sos/audit/RiskLimitForm.tsx [hunk 1]
```diff
@@ -92,6 +93,16 @@ class RiskLimitForm extends React.Component<FormProps & any, FormState> {
         );
     }
 
+    private onButtonClick = (_: number, field: string) => {
```
Comment (kiniry) [inline client/src/component/sos/audit/RiskLimitForm.tsx]: Yuck.  What a style.
