### PR TITLE
Store decimals at higher precision.

### LINKED ISSUE #491: Backend should serialize risk limit with more floating point percision
The backend is either (1) accepting a risk limit with many digits of precision (e.g. `0.04321`/`4.321 %`) but not saving it with that much precision (truncates to `0.04`), or (2) is only failing to serialize the risk limit with a higher level of precision. We should be able to accept and persist risk limits with a precision of at least one tenth of a percent. In #374, @kiniry suggests that we uses 3 decimal places. I interpret this to mean we should be able to losslessly represent, for example, `12.3 %`/`0.123`.

### PR DESCRIPTION
**Pull request by dmzimmerman**
Closes #491

### CODE REVIEW

File: server/eclipse-project/src/main/java/us/freeandfair/corla/model/DoSDashboard.java [hunk 1]
```diff
@@ -59,6 +59,16 @@
   public static final int MIN_SEED_LENGTH = 20;
   
   /**
+   * The database stored precision for decimal types.
+   */
+  public static final int PRECISION = 6;
```
Comment (kiniry) [inline server/eclipse-project/src/main/java/us/freeandfair/corla/model/DoSDashboard.java]: Why the declaration here too?

Comment (ranweiler) [reply server/eclipse-project/src/main/java/us/freeandfair/corla/model/DoSDashboard.java]: Is it something automatically consumed by Hibernate?

Comment (dmzimmerman) [reply server/eclipse-project/src/main/java/us/freeandfair/corla/model/DoSDashboard.java]: It's a symbolic constant to allow us to change it more easily rather than hunting through the fields; also useful when we eventually add a risk limit for ballot polling audits, or different risk limits for state/county, etc.

Comment (dmzimmerman) [reply server/eclipse-project/src/main/java/us/freeandfair/corla/model/DoSDashboard.java]: Of course, it wasn't actually used yet. But it is now.
