### PR TITLE
Fix multiple server issues

### LINKED ISSUE #848: manifest_hash.sql shows hash of all successfully uploaded manifests, not just most recent
E.g. if Adams successfully uploads two bm files, there will be two lines in the result of the query

SELECT co.name as county_name, uf.hash AS ballot_manifest_hash
FROM county AS co
LEFT JOIN uploaded_file AS uf 
ON co.id = uf.county_id
WHERE (hash_status = 'VERIFIED' AND status = 'IMPORTED_AS_BALLOT_MANIFEST') OR uf.county_id is NULL 
ORDER BY county_name
;

### LINKED ISSUE #858: NPE triggered by rapid server interaction
@ranweiler wrote on Slack:

```
00:07:41,502  INFO corla:406 - endpoint /ballot-not-found hit by localhost:8888
00:07:41,531 ERROR corla:462 - uncaught exception in endpoint /ballot-not-found:
java.lang.NullPointerException
    at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
    at us.freeandfair.corla.model.CVRAuditInfo.setDisagreement(CVRAuditInfo.java:253)
    at us.freeandfair.corla.controller.ComparisonAuditController.unaudit(ComparisonAuditController.java:730)
    at us.freeandfair.corla.controller.ComparisonAuditController.submitAuditCVR(ComparisonAuditController.java:536)
    at us.freeandfair.corla.endpoint.BallotNotFound.endpointBody(BallotNotFound.java:145)
    at us.freeandfair.corla.endpoint.AbstractEndpoint.endpoint(AbstractEndpoint.java:454)
    at us.freeandfair.corla.Main.lambda$activateEndpoints$5(Main.java:375)
    at spark.RouteImpl$1.handle(RouteImpl.java:72)
    at spark.http.matching.Routes.execute(Routes.java:61)
    at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
    at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
    at org.eclipse.jetty.server.Server.handle(Server.java:564)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
    at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
    at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
    at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
    at java.lang.Thread.run(Thread.java:748)

00:07:41,532 ERROR corla:506 - error 500 server error on /ballot-not-found: java.lang.NullPointerException by countyadmin1 from localhost:8888
```
with file:
```
File name: d0-n50000.csv

SHA-256 hash: 16740B3A7FFB5AC4E42764CD775300285D5AC7E6FEE1E91B956ABF5ABDB73B9B
```

all i did was click "Ballot not found" a bunch of times really fast
it accepted 2, then failed with NPEs for every other attempt

### PR DESCRIPTION
**Pull request by dmzimmerman**
Addresses multiple issues:
- null pointer exception on "unaudit" action (#858)
- inexact CVR query for listing CVRs in county/state reports
- class loading problems using the ZoneId class at runtime
- ballot manifest files that are replaced by subsequent imports not being reset to NOT_IMPORTED

Closes #848 
Closes #858 
(though the client bug that triggered #858 probably has to be addressed too)

### CODE REVIEW

File: server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/BallotManifestImport.java [hunk 1]
```diff
@@ -91,6 +91,13 @@ private void updateCountyDashboard(final Response the_response,
     if (cdb == null) {
       serverError(the_response, "could not locate county dashboard");
     } else {
+      // mark any previous ballot manifest import as NOT_IMPORTED
+      if (cdb.manifestFile() != null) {
+        cdb.manifestFile().setStatus(FileStatus.NOT_IMPORTED);
```
Comment (ranweiler) [inline server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/BallotManifestImport.java]: So this changes the meaning of `NOT_IMPORTED` to be "not both imported and active", vs. "not ever imported", right? What's the motivation for this?

Comment (dmzimmerman) [reply server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/BallotManifestImport.java]: The motivation is to accurately reflect the state of the system as it currently exists; it is not really useful to have the information that a file was imported in the past, and its data was subsequently removed from the database and replaced with that of a different file before the audit began - the only reason to reimport a file is to correct a mistake. Having the original file still be in the database, and the logs indicating what happened, is enough to document the mistake. It might be a better idea to make that enum value be `IN_USE` or `CURRENT_IMPORT` or some similar thing, but changing that at this point is problematic in other ways.
